name: Test Installer Script
on: 
  workflow_dispatch:
  
jobs:
  test-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run install script
        run: |
          chmod +x ./install.sh
          ./install.sh <<EOF
          1
          1
          j
          j
          j
          j
          j
          j
          j
          EOF
