name: Test Installer Script in English with install all on amd64
on: 
  workflow_dispatch:
  
jobs:
  test-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run install script in English with install all on amd64
        run: |
          chmod +x ./install.sh
          ./install.sh <<EOF
          2
          1
          y
          y
          y
          y
          y
          y
          y
          y
          EOF
